### Coin flips example using NumPy

source: [Udacity](https://eu.udacity.com/course/data-analyst-nanodegree--nd002)

In [5]:
# imports
import numpy as np

In [6]:
# outcome of one coin flip
np.random.randint(0,2) # note that 0 is default and could be omitted

1

In [7]:
# outcomes of ten thousand coin flips
# omitting default 0 value in .randint()
np.random.randint(2, size=10000)

array([0, 1, 0, ..., 0, 0, 0])

In [8]:
# mean outcome of fifty thousand coin flips
np.random.randint(2, size=50000).mean()

0.50061999999999995

In [9]:
# outcome of one coin flip, where we choose from an array
np.random.choice([0, 1])

1

In [11]:
# outcome of fifty thousand coin flips, no weighting
np.random.choice([0, 1], size=50000)

array([0, 1, 0, ..., 0, 1, 1])

In [12]:
# mean outcome of fifty thousand fair coin flips
np.random.choice([0, 1], size=50000).mean()

0.49614000000000003

In [13]:
# outcomes of fifty thousand biased coin flips
# p must sum to 1
np.random.choice([0, 1], size=50000, p=[0.9, 0.1])

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
# mean outcome of fifty thousand biased coin flips
np.random.choice([0, 1], size=50000, p=[0.9, 0.1]).mean()

0.10176