### Coin flips example using NumPy

Modified from the source at: [Udacity](https://eu.udacity.com/course/data-analyst-nanodegree--nd002)

In [15]:
# imports
import numpy as np

In [16]:
# outcome of one coin flip
np.random.randint(0,2) # note that 0 is default and could be omitted

1

In [17]:
# outcomes of ten thousand coin flips
# omitting default 0 value in .randint()
np.random.randint(2, size=10000)

array([1, 1, 0, ..., 1, 1, 0])

In [18]:
# mean outcome of fifty thousand coin flips
np.random.randint(2, size=50000).mean()

0.50494000000000006

In [19]:
# outcome of one coin flip, where we choose from an array
np.random.choice([0, 1])

0

In [20]:
# outcome of fifty thousand coin flips, no weighting
np.random.choice([0, 1], size=50000)

array([0, 0, 1, ..., 1, 1, 1])

In [21]:
# mean outcome of fifty thousand fair coin flips
np.random.choice([0, 1], size=50000).mean()

0.50346000000000002

In [22]:
# outcomes of fifty thousand biased coin flips
# p must sum to 1
np.random.choice([0, 1], size=50000, p=[0.9, 0.1])

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
# mean outcome of fifty thousand biased coin flips
np.random.choice([0, 1], size=50000, p=[0.9, 0.1]).mean()

0.10094